// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameUser = "user"

// User 用户
type User struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username string `gorm:"column:username;not null;comment:用户名" json:"username"`  // 用户名
	Nickname string `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`   // 昵称
	Password string `gorm:"column:password;not null;comment:密码摘要" json:"password"` // 密码摘要
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
